language: go
sudo: false
env:
  - DEP_VERSION="0.4.1"
go:
  - "1.10.x"
  #- tip
before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep
  # Install the goveralls plugin
  - go get github.com/mattn/goveralls
install:
  # install the build dependencies in the vendor directory
  - dep ensure
script:
  - $GOPATH/bin/goveralls -service=travis-ci
